// <auto-generated />
namespace EFExample.cs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class customer2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customer2));
        
        string IMigrationMetadata.Id
        {
            get { return "202002130723002_customer2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
